"""Design tokens cho giao diện desktop Báo Cáo Giao Ban."""

from __future__ import annotations

# Colors
COLOR_PRIMARY = "#1E40AF"
COLOR_SECONDARY = "#3B82F6"
COLOR_CTA = "#F59E0B"
COLOR_BACKGROUND = "#F8FAFC"
COLOR_TEXT = "#0F172A"
COLOR_SURFACE = "#FFFFFF"
COLOR_BORDER = "#E2E8F0"
COLOR_MUTED = "#475569"
COLOR_SUCCESS = "#16A34A"
COLOR_WARNING = "#D97706"
COLOR_ERROR = "#DC2626"
COLOR_NEUTRAL = "#64748B"
COLOR_WHITE = "#FFFFFF"
COLOR_PRIMARY_HOVER = "#1D4ED8"
COLOR_PRIMARY_ACTIVE = "#2563EB"
COLOR_PRIMARY_DARK = "#1E3A8A"
COLOR_STATUS_IDLE = COLOR_NEUTRAL
COLOR_STATUS_RUNNING = COLOR_SECONDARY
COLOR_STATUS_FAILED = COLOR_ERROR
COLOR_STATUS_DONE = COLOR_SUCCESS

# Fonts
FONT_HEADING = ("Cascadia Mono", 14, "bold")
FONT_HEADING_LARGE = ("Cascadia Mono", 18, "bold")
FONT_BODY = ("Segoe UI", 13)
FONT_BODY_BOLD = ("Segoe UI", 13, "bold")
FONT_SMALL = ("Segoe UI", 11)
FONT_MONO_SMALL = ("Cascadia Mono", 11)

# Layout
SIDEBAR_WIDTH = 220
TOPBAR_HEIGHT = 64
WINDOW_SIZE = "1280x820"
WINDOW_MIN_WIDTH = 1100
WINDOW_MIN_HEIGHT = 720

# Spacing
SPACING_XS = 4
SPACING_SM = 8
SPACING_MD = 12
SPACING_LG = 16
SPACING_XL = 24
SPACING_2XL = 32

# Radius / borders / shadows
RADIUS_SM = 6
RADIUS_MD = 10
RADIUS_LG = 14
BORDER_WIDTH = 1
SHADOW_CARD = "0 8 24 rgba(15, 23, 42, 0.08)"
SHADOW_ELEVATED = "0 12 32 rgba(15, 23, 42, 0.12)"
